# Customized configurations of a virtual machine

virtualbox:
  gui: false
  memory: 1024
  cpus: 2

synced_folder:
  host_path: "share"
  guest_path: "/share"

# forwarded_port:
#   - guest: 22
#     host: 2200
#   - guest: 80
#     host: 8000
#
# # If an HTTP proxy exists, set the following values before creating a VM.
#
# proxy:
#   http_proxy: "http://example.proxy.com:8080/"
#   https_proxy: "https://example.proxy.com:8080/"
#   no_proxy: "127.0.0.1,localhost"
