# Customized configurations of a virtual machine
#
# If you customize configurations, copy this file to `config.yml` and edit it.

memory: 1024
cpus: 2

# http_proxy: "http://example.proxy.com:8080/"
# https_proxy: "https://example.proxy.com:8080/"
# no_proxy: "127.0.0.1,localhost"
